import type { ReviewReport } from "./types";

function statusGlyph(status: string): string {
  if (status === "pass") return "✅";
  if (status === "warn") return "⚠️";
  if (status === "fail") return "❌";
  return "⏭️";
}

export function reportToMarkdown(report: ReviewReport): string {
  const lines: string[] = [];

  lines.push(`# Prompt Review Report`);
  lines.push("");
  lines.push(`**Target:** ${report.label}`);
  lines.push(`**Reviewed:** ${report.createdAt}`);
  lines.push(`**Size:** ${report.promptWords} words · ${report.promptChars} chars · ${report.toolCount} tools`);
  lines.push("");
  lines.push(`## Overall`);
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Score | **${report.overall.score} / 100** |`);
  lines.push(`| Grade | **${report.overall.grade}** |`);
  lines.push(`| Clarity | ${report.clarity.score}/100 |`);
  lines.push(`| Ambiguity phrases | ${report.ambiguity.count} |`);
  lines.push(
    `| Injection surface | ${report.injection.level} (${report.injection.score}/100 · ${report.injection.defensesPresent}/${report.injection.defensesTotal} defenses) |`,
  );
  lines.push(
    `| Failure modes named | ${report.failureModes.length} (${report.failureModes.filter((f) => f.coveredInPrompt).length} covered) |`,
  );
  lines.push(`| Rewrite ready | ${report.rewriteReady ? "Yes" : "No"} |`);
  lines.push("");

  lines.push(`## Breakdown`);
  lines.push("");
  for (const cat of report.categories.filter((c) => c.checks.some((k) => k.status !== "skip"))) {
    lines.push(`### ${cat.label} (${cat.score}/100)`);
    lines.push("");
    for (const c of cat.checks.filter((k) => k.status !== "skip")) {
      lines.push(`- ${statusGlyph(c.status)} **${c.label}** — ${c.detail}`);
    }
    lines.push("");
  }

  if (report.ambiguity.hits.length) {
    lines.push(`## Ambiguity hits`);
    lines.push("");
    for (const hit of report.ambiguity.hits.slice(0, 20)) {
      lines.push(`- **“${hit.phrase}”** — ${hit.reason}`);
      lines.push(`  - Suggestion: ${hit.suggestion}`);
    }
    lines.push("");
  }

  lines.push(`## Failure modes`);
  lines.push("");
  for (const fm of report.failureModes) {
    lines.push(
      `- ${fm.coveredInPrompt ? "✅" : "⚠️"} **${fm.title}** (${fm.risk}) — ${fm.why}`,
    );
    if (!fm.coveredInPrompt) lines.push(`  - Mitigation: ${fm.mitigation}`);
  }
  lines.push("");

  if (report.recommendations.length) {
    lines.push(`## Recommendations`);
    lines.push("");
    for (const rec of report.recommendations) {
      lines.push(`### ${rec.priority.toUpperCase()}: ${rec.title}`);
      lines.push("");
      lines.push(`**Issue**`);
      lines.push("");
      lines.push(rec.issue);
      lines.push("");
      lines.push(`**Why it matters**`);
      lines.push("");
      lines.push(rec.why);
      lines.push("");
      lines.push(`**Suggested fix**`);
      lines.push("");
      lines.push(rec.fix);
      if (rec.reference) {
        lines.push("");
        lines.push(`**Reference:** ${rec.reference}`);
      }
      lines.push("");
    }
  }

  if (report.rewrites.length) {
    lines.push(`## Suggested rewrites`);
    lines.push("");
    for (const rw of report.rewrites) {
      lines.push(`### ${rw.section}`);
      lines.push("");
      lines.push(rw.rationale);
      lines.push("");
      lines.push("```");
      lines.push(rw.after.trim());
      lines.push("```");
      lines.push("");
    }
  }

  if (report.nextSteps.length) {
    lines.push(`## Next steps`);
    lines.push("");
    for (const s of report.nextSteps) lines.push(`- ${s}`);
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`Generated by ARC Labs Prompt Reviewer`);
  return lines.join("\n");
}
